In [46]:
import torch
import numpy as np
A=torch.tensor([[2.0,5.0],[5.0,6.0],[0.0,0.0]])
Z=torch.tensor([[0.5,0.5],[0.5,0.5],[0.5,0.5]])

B=list(np.array([2.0,3.0]))
print(B)


[2.0, 3.0]


In [47]:
norm=torch.norm(A,dim=1)
B=A.clone()
B[norm>0.0001]=A[norm>0.0001]/norm.unsqueeze(-1)[norm>0.0001]
print(torch.norm(B,dim=1))

print(B)

tensor([1., 1., 0.])
tensor([[0.3714, 0.9285],
        [0.6402, 0.7682],
        [0.0000, 0.0000]])


In [27]:
Z=torch.tensor([[1.1]])
print(Z.shape)
print(Z.squeeze(0))

torch.Size([1, 1])
tensor([1.1000])


In [12]:
print(A.norm(dim=1))

tensor([5.3852, 7.8102, 1.4142])


In [30]:
A=torch.tensor([[2.,3.],[5.,6.]])

Z=torch.tensor([4.,2.])
B=torch.diag(Z)
print(B)

F=torch.cat((A,B))
print(F)

tensor([[4., 0.],
        [0., 2.]])
tensor([[2., 3.],
        [5., 6.],
        [4., 0.],
        [0., 2.]])


In [25]:
print(Z**2)
Z1=torch.tensor([1.,1.])
Norm=Z**2+Z1**2
print(Norm)
print(Norm**(0.5))

tensor([16.,  4.])
tensor([17.,  5.])
tensor([4.1231, 2.2361])


In [33]:

print(A.t())

Z.matmul(A.t())

tensor([[2., 5.],
        [3., 6.]])


tensor([14., 32.])

In [34]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
leaspy_path = os.path.join(os.getcwd(), '..', '..')
sys.path.append(leaspy_path)

from leaspy import Leaspy, Data, AlgorithmSettings, IndividualParameters

In [39]:
df = pd.read_csv(os.path.join('inputs', 'data.csv'))

# —— Feature 1
df['Feature 1'] = df['Feature 1']/100

# —— Feature 2
df['Feature 2'] = df['Feature 2']/100

# —— Feature 3
df['Feature 3'] = -df['Feature 3']/100+1

# —— Feature 4
df['Feature 4'] = -df['Feature 4']/100+1

# —— Let's select patient with at least two visits
df = df.set_index(['ID', 'TIME'])
indices = [idx for idx in df.index.unique('ID') if df.loc[idx].shape[0] >= 2]
df = df[df.index.get_level_values(0).isin(indices)]

# —— Store the data into a Data object
data = Data.from_dataframe(df)

FileNotFoundError: [Errno 2] No such file or directory: 'inputs/data.csv'