In [1]:
import torch
import numpy as np

In [17]:
T=[[[float("NaN"),float("NaN")],[3.0,4.0]],[[2.0,2.0],[1.0,2.0]]]
V=torch.tensor(T)
print(V)
print(torch.norm(V,p=2,dim=2))

tensor([[[nan, nan],
         [3., 4.]],

        [[2., 2.],
         [1., 2.]]])
tensor([[   nan, 5.0000],
        [2.8284, 2.2361]])


In [19]:
V[V==V].reshape(3,2)

tensor([[3., 4.],
        [2., 2.],
        [1., 2.]])

In [13]:
V[V==V].flatten()

tensor([2., 1., 2., 2., 2., 1., 2.])

In [60]:
S=[[3.0,2.0],[1.0,2.0]]
g=torch.tensor(S).unsqueeze(-2).numpy()

Z=torch.ones(2).reshape((-1,1)).numpy()

print(np.transpose(np.kron(Z,g),axes=(0,1,2)))

[[[3. 2.]
  [3. 2.]]

 [[1. 2.]
  [1. 2.]]]


In [65]:
np.sum(g,axis=0)

array([[4., 4.]], dtype=float32)

In [66]:
D=torch.tensor(S)

V=torch.tensor([2.1,2.0])

print(torch.matmul(V,D))

tensor([8.3000, 8.2000])
