In [37]:
import torch
import numpy as np
os.chdir("/Users/samuel.gruffaz/Documents/PEcollab")
import leaspy.models.utils.OptimB as OptimB

In [2]:
T=[[[float("NaN"),float("NaN")],[3.0,4.0]],[[2.0,2.0],[1.0,2.0]]]
V=torch.tensor(T)
print(V)
print(torch.norm(V,p=2,dim=2))

tensor([[[nan, nan],
         [3., 4.]],

        [[2., 2.],
         [1., 2.]]])
tensor([[   nan, 5.0000],
        [2.8284, 2.2361]])


In [19]:
sig=0.2
dim=3

nk=int(1/sig)
grid1=torch.linspace(-0.5*sig,(nk+0.5)*sig,nk+1)
L=[grid1]*dim
T=torch.meshgrid(L)
shape=list(T[0].shape)
shape.append(dim)
Per=[]
for j in range(len(shape)):
    Per.append(j)
Per[-1],Per[0]=Per[0],Per[-1]
Z=torch.zeros(shape)
Per=tuple(Per)
Z=Z.permute(Per)
for j in range(dim):
    Z[j]=T[j]
Z=Z.permute(Per)

Z=Z.reshape((-1,dim))


#for j in range(dim):
    #Z[]
index=[]
for j in range(len(Z)):
    A=Z[j]
    dist=torch.norm(Z-A,dim=1)
    m=dist.min().item()
    if m<sig:
        index.append(j)
X_con=Z[index]
print(index)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215]


In [26]:
A=torch.arange(10)
B=torch.zeros(2,10)
B[0]=A
B[1]=A
#B=B.permute(1,0)
print(B)
print(B.reshape((-1,)))

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0., 1., 2., 3., 4., 5., 6., 7.,
        8., 9.])


In [35]:
from scipy.linalg import block_diag
np.kron(np.eye(3,dtype=int),np.ones((2,2)))

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [16]:
dis=torch.norm(Z,dim=1)
print(dis.min().item())

0.17320507764816284


In [1]:
D={"B":1.4,"D":2.3}

print("B" in D)

True


In [19]:
V[V==V].reshape(3,2)

tensor([[3., 4.],
        [2., 2.],
        [1., 2.]])

In [21]:
T=[[[1.0,float("NaN")],[3.0,4.0]],[[2.0,2.0],[1.0,2.0]]]
V=torch.tensor(T)

In [28]:
Z=(V==V).all(axis=2)
print(Z)

V[Z]

tensor([[False,  True],
        [ True,  True]])


tensor([[3., 4.],
        [2., 2.],
        [1., 2.]])

In [38]:
T=[[[1.0,float("NaN")],[float("NaN"),float("NaN")]],[[2.0,2.0],[1.0,2.0]]]
V=torch.tensor(T)
XT=V

In [39]:
X1,Y1=OptimB.filtre_nan_inhomogene(V,V,mask)

NameError: name 'mask' is not defined

In [36]:
(XT!=XT).any(axis=2)*(XT==XT).any(axis=2)

tensor([[ True, False],
        [False, False]])

In [60]:
S=[[3.0,2.0],[1.0,2.0]]
g=torch.tensor(S).unsqueeze(-2).numpy()

Z=torch.ones(2).reshape((-1,1)).numpy()

print(np.transpose(np.kron(Z,g),axes=(0,1,2)))

[[[3. 2.]
  [3. 2.]]

 [[1. 2.]
  [1. 2.]]]


In [65]:
np.sum(g,axis=0)

array([[4., 4.]], dtype=float32)

In [66]:
D=torch.tensor(S)

V=torch.tensor([2.1,2.0])

print(torch.matmul(V,D))

tensor([8.3000, 8.2000])


In [5]:
def FiltreNanHomogène(XT,Y):
    """
    Prend en entrée XT (nb_patient,nb_visit_max,dim) et retourne X sous la forme (nb_visit,dim)

    Si un vecteur contient un Nan dans ses coordonnées on le retire

    """


    Select=((XT==XT).all(axis=2))*(Y==Y).all(axis=2)#fonctionne bien voir notebook test pour se convaincre
    
    return XT[Select],Y[Select]

In [9]:
X,Y=FiltreNanHomogène(V,V)

In [7]:
def Sub_sampling(X,k):
    """
    Prend X le tensor (nb_visite,dim) et sélectionne k points bien espacé renvoyé dans un tensor (k,dim)


    """
    Center,index=kmeans_plus_plus(X.numpy(), k)
    return torch.from_numpy(Center),index

In [27]:
X.repeat(3,1,1)

tensor([[[3., 4.],
         [2., 2.],
         [1., 2.]],

        [[3., 4.],
         [2., 2.],
         [1., 2.]],

        [[3., 4.],
         [2., 2.],
         [1., 2.]]])

In [34]:
def Matrix(X,Xgrand,meta_settings):
    """
    X est la donnée des points de controles un tensor de la forme (k,nb_dim) (k nombre de visite après subsampling), kernelname le nom du noyau à utiliser
    cette fonction renvoie la matrice K_X=(k(x_i,x_j)) i <nb_visit+1, j<k+1
    On a Xgrand (nb_visit,nb_dim) les points de controle sans subsampling
    """
    kernelname=meta_settings["kernelname"]
    sigma=meta_settings["sigma"]
    k=len(X)
    nb_visit=len(Xgrand)
    
    
    if kernelname=="RBF":#le calcul est fait sans approximations
        sigma=meta_settings["sigma"]
        

        PA1=Xgrand.repeat(k,1,1)
        PA2=X.repeat(nb_visit,1,1).permute(1,0,2)

        PA3=PA1-PA2

        K_X=torch.exp(-torch.norm(PA3,dim=2)**2/(2*sigma**2))
    else:
        raise ValueError("Le nom de noyau est mauvais ! ")

    return K_X

In [35]:
Matrix(X,A,{"sigma":2.0,"kernelname":"RBF"})

tensor([[1.0000, 0.5353],
        [0.5353, 1.0000],
        [0.3679, 0.8825]], dtype=torch.float64)

In [42]:
X1=X.repeat(2,1,1).permute(1,0,2)

X2=A.repeat(3,1,1)





print(A)

print(A.transpose(0,1))

tensor([[3., 4.],
        [2., 2.]], dtype=torch.float64)
tensor([[3., 2.],
        [4., 2.]], dtype=torch.float64)


In [20]:
def dist(data, centers):
    distance = np.sum((np.array(centers) - data[:, None, :])**2, axis = 2)
    return distance
def kmeans_plus_plus(X, k):
    '''Initialize one point at random.
    loop for k - 1 iterations:
        Next, calculate for each point the distance of the point from its nearest center. Sample a point with a 
        probability proportional to the square of the distance of the point from its nearest center.'''
    centers = []
    index=[]
    
    # Sample the first point
    initial_index = np.random.choice(range(X.shape[0]), )
    index.append(initial_index)
    centers.append(X[initial_index, :].tolist())
    
    print('max: ', np.max(np.sum((X - np.array(centers))**2)))
    
    # Loop and select the remaining points
    for i in range(k - 1):
        print(i)
        distance = dist(X, np.array(centers))
        
        if i == 0:
            pdf = distance/np.sum(distance)
            indexcour=np.random.choice(range(X.shape[0]), replace = False, p = pdf.flatten())
            centroid_new = X[indexcour]
            index.append(indexcour)
        else:
            # Calculate the distance of each point from its nearest centroid
            dist_min = np.min(distance, axis = 1)
            
            pdf = dist_min/np.sum(dist_min)
# Sample one point from the given distribution
            indexcour=np.random.choice(range(X.shape[0]), replace = False, p = pdf)
            centroid_new = X[indexcour]
            index.append(indexcour)
            

        centers.append(centroid_new.tolist())
        
    return np.array(centers),index

In [21]:
A,B=Sub_sampling(X,2)

print(A)

max:  13.0
0
tensor([[3., 4.],
        [2., 2.]], dtype=torch.float64)


In [145]:
def TransformationB(W,Control,meta_settings):
    """
    Prend en entrée la matrice des poids, et les points de contrôles "Control" ainsi que meta_settings pour avoir des
    informations sur le noyau, W de forme (nb_controle,nb_features). On renvoie la fonction associée pour update B.

    #les poids des features i, c'est la colonne i de W
    """
    if meta_settings["kernelname"]=="RBF":
        sigma=meta_settings["sigma"]
        def function(x):
            """
            x doit être de la forme (n1,n2,n_dim) ou (n_1,n_dim)

            """
            
            nb_dim=len(x.shape)
            if nb_dim==3:
                Control1=Control.repeat(x.shape[0],x.shape[1],1,1)
                x1=x.unsqueeze(2)
                
                
                KK=torch.exp(-torch.norm(Control1-x1,dim=nb_dim)**2/(2*sigma**2))
                print(KK)
                #fonctionne pour W dim 1
                W1=W.double()
                Fin=torch.matmul(KK,W1)
                return Fin
            elif nb_dim==2:#Si on prend une liste
                Control1=Control.repeat(x.shape[0],1,1)
                x1=x.unsqueeze(1)
                print("x1")
                print(x1)
                print("Control1")
                print(Control1)
                
                KK=torch.exp(-torch.norm(Control1-x1,dim=nb_dim)**2/(2*sigma**2))
                print(KK)
                #à vérifier le reset
                W1=W.double()
                Fin=torch.matmul(KK,W1)
                return Fin# de même dimension que x
            else:
                raise ValueError("La valeur de x a une mauvaise shape, les formats acceptés sont (n,dim) ou (n1,n2 ,dim) ")
            


           
           
        return function
    else:
        raise ValueError("Le nom de noyau est mauvais ! ")

In [150]:
Control=A
meta_settings={"sigma":2.0,"kernelname":"RBF"}
W=torch.tensor([[3.0,4.0],[3.0,3.0]])
#W=torch.tensor([2.0,3.0])
#les poids des features i, c'est la colonne i de W
fonc=TransformationB(W,Control,meta_settings)

print(V)
print(Control)

print(fonc(V))

tensor([[[1.0000, 2.5000],
         [3.0000, 4.0000]],

        [[2.0000, 2.0000],
         [1.0000, 2.0000]]])
tensor([[3., 4.],
        [2., 2.]], dtype=torch.float64)
tensor([[[0.4578, 0.8553],
         [1.0000, 0.5353]],

        [[0.5353, 1.0000],
         [0.3679, 0.8825]]], dtype=torch.float64)
tensor([[[3.9395, 4.3974],
         [4.6058, 5.6058]],

        [[4.6058, 5.1410],
         [3.7511, 4.1190]]], dtype=torch.float64)


In [83]:
T=[[[1.0,2.5],[3.0,4.0]],[[2.0,2.0],[1.0,2.0]]]
V=torch.tensor(T)

In [102]:
C=A.repeat(2,2,1,1)
print(C)
print(V.unsqueeze(2))
print(C-V.unsqueeze(2))

tensor([[[[3., 4.],
          [2., 2.]],

         [[3., 4.],
          [2., 2.]]],


        [[[3., 4.],
          [2., 2.]],

         [[3., 4.],
          [2., 2.]]]], dtype=torch.float64)
tensor([[[[1.0000, 2.5000]],

         [[3.0000, 4.0000]]],


        [[[2.0000, 2.0000]],

         [[1.0000, 2.0000]]]])
tensor([[[[ 2.0000,  1.5000],
          [ 1.0000, -0.5000]],

         [[ 0.0000,  0.0000],
          [-1.0000, -2.0000]]],


        [[[ 1.0000,  2.0000],
          [ 0.0000,  0.0000]],

         [[ 2.0000,  2.0000],
          [ 1.0000,  0.0000]]]], dtype=torch.float64)
